import type { components } from './schema'

type Schemas = components['schemas']

export type Me = Schemas['Me']
export type Role = Schemas['Role']
export type Language = Schemas['Language']
export type Severity = Schemas['Severity']
export type SeverityCounts = Schemas['SeverityCounts']
export type DataQuality = Schemas['DataQuality']
export type SyncStatus = Schemas['SyncStatus']
export type SensorParameter = Schemas['SensorParameter']
export type SensorValue = Schemas['SensorValue']
export type ParameterRange = Schemas['ParameterRange']
export type PondWaterQualityRow = Schemas['PondWaterQualityRow']
export type FarmDetail = Schemas['FarmDetail']
export type Alert = Schemas['Alert']
export type AlertState = Schemas['AlertState']
export type OperationalStatus = Schemas['OperationalStatus']
export type ReportStatusSummary = Schemas['ReportStatusSummary']
export type ReportStatusItem = Schemas['ReportStatusItem']
export type ReportListItem = Schemas['ReportListItem']
export type PasswordToken = Schemas['PasswordToken']
export type Problem = Schemas['Problem'] & { remainingAttempts?: number; lockedUntil?: string }
export type PondListRow = Schemas['PondListRow']
export type GrowthJudgement = Schemas['GrowthJudgement']
export type GrowthTargetPoint = Schemas['GrowthTargetPoint']
export type SamplingRecord = Schemas['SamplingRecord']
export type SamplingMeasurement = Schemas['SamplingMeasurement']
export type FarmSummary = Schemas['FarmSummary']
export type Issue = Schemas['Issue']
